memeSubreddits = [
    "dankmemes",
    "memeeconomy",
    "deepfriedmemes",
    "surrealmemes",
    "offensivememes",
    "2meirl4meirl",
    "blackpeopletwitter",
    "okbuddyretard",
    "coaxedintoasnafu",
    "bikinibottomtwitter",
    "bonehurtingjuice",
    "iamverysmart",
    "me_irl",
    "meirl",
    "memes",
    "memes_of_the_dank",
    "anime_irl",
    "animemes",
    "notgayporn",
    "suddenlygay",
    "ihavesex",
    "dank_meme",
    "edgymemes",
    "wholesomememes",
    "historymemes",
    "ligma",
    "softwaregore",
    "turkeyjerky"
]

memeSubs = "\n".join(memeSubreddits[:])

yardim = {
    "komutlar" :    "```asciidoc\n== Hmn-Bot Komutları ==\n\n",
    "eglence" :     "\n== Eğlence ==\n",
    "genel" :       "\n== Genel ==\n",
    "yonetim" :     "== Yönetim ==\n",
    "bitis" :       "```",
    "surum" :       "!sürüm,!version    :: bot sürümünü gösterir\n",
    "statu" :       "!statü,!stats      :: bot istatistiklerini gösterir\n",
    "destek" :      "!destek            :: destek sunucusu davet linki gönderir\n",
    "server" :      "!server            :: server bilgilierini gösterir\n",
    "temizle":      "!temizle           :: kanaldaki son x mesajı temizler\n",
    "hava" :        "!hava              :: istenilen şehirdeki hava durumunu gösterir\n",
    "roller" :      "!roller            :: serverdaki rolleri listeler\n",
    "rolver" :      "!rolver            :: etiketlenen kullanıcılara rol verir\n",
    "gelistirici" : "!dev,!geliştirici  :: geliştirici bilgilerini gösterir\n",
    "sence" :       "!sence             :: evet-hayır sorularına cevap verir\n",
    "google" :      "!google,!ara       :: google'da arama linki oluşturur\n",
    "meme" :        "!meme              :: seçilen subredditten rastgele bir meme gönderir\n",
    "davet" :       "!davet,!invite     :: bulunulan kanal için x adet davet linki oluşturur\n",
    "lmgtfy" :      "!lmgtfy            :: lmgtfy ile arama linki oluşturur\n",
    "btc" :         "!bitcoin,!btc      :: bitcoin kurunu gösterir\n" ,
    "kripto" :      "!kripto,!crypto    :: istenilen kripto para kurunu gösterir\n",
    "doviz" :       "!döviz             :: istenilen döviz kurunu gösterir\n",
    "xdoviz" :      "!xdöviz            :: istenilen döviz kuru hakkinda detayli bilgi gosterir\n",
    "oyun"  :       "!oyun              :: o sırada kimlerin x oyununu oynadığını gösterir\n",
    "ceviri":       "!cevir             :: dilden dile çeviri yapar\n",
    "avatar":       "!avatar            :: etiketlenen ya da ismi geçen kullanıcının avatarını gösterir\n",
    "oyla" :        "!oyla,!vote        :: bir oylama başlatır\n",
    "soz" :         "!soz,!lyrics       :: istenilen şarkının sözlerini gösterir\n",
    "yardim" :      "!yardim,!help      :: bir komut hakkında yardımı gösterir (!yardım <komut>)\n",
    "leet" :        "!leet,!l33t        :: yazılarınızı h4v4l1 yapar\n",
    "firlat" :      "!fırlat,!flip      :: bozuk para fırlatır\n",
    "sikayet" :     "!şikayet           :: server sahibine şikayet yollar\n",
    "karakter" :    "\nNot: Türkçe komutları türkçe karakter kullanmadan da çalıştırabilirsiniz.\n(!sürüm == !surum, !döviz usd == !doviz usd)"
}


komutYardim = {
    "stats" :       "```asciidoc\n== !stats komutu ==\n\nAçıklama : Botun istatistiklerini gösterir\n\nÖrnek : !statu```",
    "destek" :      "```asciidoc\n== !destek komutu ==\n\nAçıklama : Hmn-Bot hakkında önerileriniz ya da sorunlarınız için destek sunucusunun davet linkini gönderir\n\nÖrnek : !destek```",
    "server" :      "```asciidoc\n== !server komutu ==\n\nAçıklama : Bulunulan serverın bilgilerini gösterir\n\nÖrnek : !server```",
    "temizle":      "```asciidoc\n== !temizle komutu ==\n\nAçıklama : Belirtilen miktarda mesajı kanaldan siler. En fazla 99 mesaj silebilir.\n\nÖrnek : !temizle 10```",
    "hava" :        "```asciidoc\n== !hava komutu ==\n\nAçıklama : Belirtilen şehirdeki hava durumunu gösterir\n\nÖrnek : !hava Istanbul | !hava Berlin```",
    "roller" :      "```asciidoc\n== !roller komutu ==\n\nAçıklama : Bulunulan serverdaki rolleri listeler\n\nÖrnek : !roller```",
    "rolver" :      "```asciidoc\n== !rolver komutu ==\n\nAçıklama : Etiketlenen kullanıcıya etiketlenen rolü verir\n\nÖrnek : !rolver @Hmn-Bot @Bot```",
    "gelistirici" : "```asciidoc\n== !geliştirici komutu ==\n\nAçıklama : Geliştirici bilgilerini gösterir\n\nÖrnek : !geliştirici | !dev```",
    "geliştirici" : "```asciidoc\n== !geliştirici komutu ==\n\nAçıklama : Geliştirici bilgilerini gösterir\n\nÖrnek : !geliştirici | !dev```",
    "dev" :         "```asciidoc\n== !dev komutu ==\n\nAçıklama : Geliştirici bilgilerini gösterir\n\nÖrnek : !geliştirici | !dev```",
    "soz" :         "```asciidoc\n== !söz komutu ==\n\nAçıklama : Girilen şarkının sözlerini gösterir\n\nÖrnek : !soz Thriller | !lyrics Human - Rag'n'Bone Man```",
    "söz" :         "```asciidoc\n== !söz komutu ==\n\nAçıklama : Girilen şarkının sözlerini gösterir\n\nÖrnek : !soz Thriller | !lyrics Human - Rag'n'Bone Man```",
    "lyrics" :      "```asciidoc\n== !lyrics komutu ==\n\nAçıklama : Girilen şarkının sözlerini gösterir\n\nÖrnek : !soz Thriller | !lyrics Human - Rag'n'Bone Man```",
    "sence" :       "```asciidoc\n== !sence komutu ==\n\nAçıklama : Bir evet-hayır sorusunu cevaplar\n\nÖrnek : !sence Bugün yağmur yağar mı?```",
    "google" :      "```asciidoc\n== !google komutu ==\n\nAçıklama : Girilen kelimelerle arama linki oluşturur\n\nÖrnek : !google Reverse Engineering nedir? | !ara Dennis Ritchie```",
    "ara" :         "```asciidoc\n== !ara komutu ==\n\nAçıklama : Girilen kelimelerle arama linki oluşturur\n\nÖrnek : !google Reverse Engineering nedir? | !ara Dennis Ritchie```",
    "meme" :        "```asciidoc\n== !meme komutu ==\n\nAçıklama : Girilen subredditten rastgele bir meme gönderir\nEk parametreler : top (seçilen subredditteki top postu gönderir) \n\nDesteklenen Subredditler : \n\n" + memeSubs +"\n\nÖrnek : !meme dankmemes top | !meme turkeyjerky```",
    "davet" :       "```asciidoc\n== !davet komutu ==\n\nAçıklama : Bulunulan kanal için x kullanımlık davet linki oluşturur\n\nÖrnek : !davet 10```",
    "invite" :      "```asciidoc\n== !invite komutu ==\n\nAçıklama : Bulunulan kanal için x kullanımlık davet linki oluşturur\n\nÖrnek : !davet 10```",
    "lmgtfy" :      "```asciidoc\n== !lmgtfy komutu ==\n\nAçıklama : Girilen kelimelerle lmgtfy linki oluşturur\n\nÖrnek : !lmgtfy How to use Google```",
    "btc" :         "```asciidoc\n== !btc komutu ==\n\nAçıklama : Bitcoin kurunu gösterir\n\nÖrnek : !bitcoin | !btc```",
    "bitcoin" :     "```asciidoc\n== !bitcoin komutu ==\n\nAçıklama : Bitcoin kurunu gösterir\n\nÖrnek : !bitcoin | !btc```",
    "kripto" :      "```asciidoc\n== !kripto komutu ==\n\nAçıklama : Girilen kripto para kurunu gösterir\n\nÖrnek : !kripto monero | !kripto xmr```",
    "crypto" :      "```asciidoc\n== !kripto komutu ==\n\nAçıklama : Girilen kripto para kurunu gösterir\n\nÖrnek : !kripto monero | !kripto xmr```",
    "doviz" :       "```asciidoc\n== !döviz komutu ==\n\nAçıklama : Girilen döviz kurunu gösterir\n\nÖrnek : !döviz dolar 20 | !döviz euro\n!döviz altın | !doviz ruble```",
    "döviz" :       "```asciidoc\n== !döviz komutu ==\n\nAçıklama : Girilen döviz kurunu gösterir\n\nÖrnek : !döviz dolar 20 | !döviz euro\n!döviz altın | !doviz ruble```",
    "xdoviz" :      "```asciidoc\n== !xdöviz komutu ==\n\nAçıklama : Girilen döviz kurunu gösterir\n\nÖrnek : !xdöviz dolar 20 | !xdöviz EUR\n!xdöviz altın | !xdoviz ruble```",
    "xdöviz" :      "```asciidoc\n== !xdöviz komutu ==\n\nAçıklama : Girilen döviz kurunu gösterir\n\nÖrnek : !xdöviz dolar 20 | !xdöviz EUR\n!xdöviz altın | !xdoviz ruble```",
    "cevir":        "```asciidoc\n== !çeviri komutu ==\n\nAçıklama : İstenilen dilden istenilen dile çeviri yapar\n\n\nÖrnek : !cevir -fr -en J'aime mon vie (fransızcadan ingilizceye çeviri yapar)\n\nÖrnek : !cevir -en Konnichiwa (algılanan dilden(japonca) ingilizceye çeviri yapar\n\nÖrnek : !cevir Conscious (algılanan dilden (ingilizce) türkçe'ye çeviri yapar```",
    "çevir":        "```asciidoc\n== !çeviri komutu ==\n\nAçıklama : İstenilen dilden istenilen dile çeviri yapar\n\nÖrnek : !cevir -fr -en J'aime mon vie (fransızcadan ingilizceye çeviri yapar)\n\nÖrnek : !cevir -en Konnichiwa (algılanan dilden(japonca) ingilizceye çeviri yapar\n\nÖrnek : !cevir Conscious (algılanan dilden (ingilizce) türkçe'ye çeviri yapar```",
    "avatar":       "```asciidoc\n== !avatar komutu ==\n\nAçıklama : Kullanıcı avatarını gösterir\n\nÖrnek : !avatar @Kullanici Sunucudaki etkietlenen kullanıcının avatarını gösterir\n\nÖrnek : !avatar KullanıcıAdı Sunucudaki kullanıcının avatarını gösterir```",
    "oyun":         "```asciidoc\n== !oyun komutu ==\n\nAçıklama : Bulunulan sunucuda, o sırada kimlerin x oyununu oynadığını gösterir\n\nÖrnek : !oyun osu!\n\nÖrnek : !oyun Starcraft```",
    "oyla" :        "```asciidoc\n== !oyla komutu ==\n\nAçıklama : Girilen bir durum için oylama başlatır\n\nÖrnek : !oyla Servera yeni kanal eklemeli miyim?```",
    "vote" :        "```asciidoc\n== !oyla komutu ==\n\nAçıklama : Girilen bir durum için oylama başlatır\n\nÖrnek : !oyla Servera yeni kanal eklemeli miyim?```",
    "leet" :        "```asciidoc\n== !leet komutu ==\n\nAçıklama : Yazdıklarınızı leet alfabesine uyarlar\n\nÖrnek : !leet Selam```",
    "l33t" :        "```asciidoc\n== !leet komutu ==\n\nAçıklama : Yazdıklarınızı leet alfabesine uyarlar\n\nÖrnek : !leet Selam```",
    "firlat" :      "```asciidoc\n== !fırlat komutu ==\n\nAçıklama : Bir bozuk para fırlatır\n\nÖrnek : !fırlat | !flip```",
    "flip" :        "```asciidoc\n== !flip komutu ==\n\nAçıklama : Bir bozuk para fırlatır\n\nÖrnek : !fırlat | !flip```",
    "sikayet" :     "```asciidoc\n== !şikayet komutu ==\n\nAçıklama : Server sahibine şikayet gönderir\n\nÖrnek : !sikayet Kanalda spam yapılıyor```",
    "şikayet" :     "```asciidoc\n== !şikayet komutu ==\n\nAçıklama : Server sahibine şikayet gönderir\n\nÖrnek : !sikayet Kanalda spam yapılıyor```",
    "yardim" :      "```asciidoc\n== !yardim komutu ==\n\nAçıklama : Bu komutu kullanmayı zaten biliyorsun :D\n\nÖrnek : !yardim cevir```",
    "yardım" :      "```asciidoc\n== !yardim komutu ==\n\nAçıklama : Bu komutu kullanmayı zaten biliyorsun :D\n\nÖrnek : !yardim cevir```",
    "help" :        "```asciidoc\n== !help komutu ==\n\nAçıklama : Bu komutu kullanmayı zaten biliyorsun :D\n\nÖrnek : !help cevir```"
}


komut = {
    #yardim["ceviri"]
    "yardim" : yardim["komutlar"] + yardim["yonetim"] + yardim["sikayet"] + yardim["rolver"] + yardim["temizle"]+ yardim["genel"] + yardim["yardim"] + yardim["avatar"] + yardim["oyla"]  + yardim["oyun"] +  yardim["soz"] + yardim["ceviri"] +yardim["google"] + yardim["lmgtfy"] + yardim["doviz"] + yardim["xdoviz"] + yardim["kripto"] + yardim["btc"] + yardim["davet"] + yardim["server"] + yardim["roller"] +  yardim["gelistirici"]  +yardim["statu"] + yardim["surum"] + yardim["destek"] + yardim["eglence"] + yardim["meme"] + yardim["sence"] + yardim["leet"] + yardim["bitis"] + yardim["karakter"],
    "join_sahip" : "Merhaba %s!\nSana ve Serverdaki **%d** kullanıcıya yardımcı olmaya hazırım! Tek yapman gereken !yardım yazarak komutlarımı öğrenmek.",
    "gelistirici" : "Merhaba <@%s>, <@%s> tarafından geliştiriliyorum.\n\n **GitHub** : https://github.com/humanova\n **Steam** : http://steamcommunity.com/id/humanovan",
    "statu" : "%d Serverda,\n%d Kullaniciya,\n%d Kanala hizmet veriyorum!",
    "sikayet_admin" : "[ŞIKAYET]\nTarih : %s\nServer : %s\nKanal : %s\nKullanıcı : %s(%s)\n\nŞikayet : %s",
    "sikayet_kullanici" :  "Şikayet iletildi!",
    "sikayet_hata" : "Şikayet iletilemedi, yeniden deneyin.",
    "durt" : "<@%s>, <@%s> seni dürttü!",
    "durt2" : "<@%s> Kendi kendini dürttün!",
    "oyla" : '<@%s> bir oylama başlattı!\n"**%s**"',
    "bitcoin" : "Bitcoin değeri : $  %s\nBitcoin değeri : TL %s",
    "kripto" : "%s değeri : $ %s\n%s değeri : TL %s",
    "doviz" : "%s/TL : %s",
    "roller" : "**%s | Server Rolleri:** ```%s```",
    "rolverHata" : "Rol verilirken hata oluştu (Bunun nedeni yetkimin olmaması olabilir!)",
    "rolverHataYetkiYok" : "**Buna yetkin yok!**",
    "server1" : "**Server Adi :** %s \n**Server ID :** %s \n**Server Sahibi :** %s(%s)\n**Kullanici Sayisi :** %d\n**Server Bolgesi :** %s\n**Server Yaratilma Tarihi :** %s",
    "lyrics" : "```asciidoc\n== %s ==\n\n%s",
    "sence1" : "Maalesef evet...",
    "sence2" : "Evet! Kesinlikle",
    "sence3" : "Hayır, bu doğru olamaz",
    "sence4" : "Maalesef hayır...",
    "memeHata" : "Subreddit anlaşılamadı. **_!yardim meme_** yazarak geçerli subredditleri görebilirsiniz.",
    "oyunHata" : "Girdiğiniz oyun ismi çok kısa. Bu nedenle arama yapamıyorum. :(",
    "oyunHata2" : "Sunucuda kimse %s oynamıyor.",
    "redditico" : "http://puu.sh/C2Lxd/78e8e9a31b.png",
    "112_pasta_url" : "https://paste.ee/p/8JKSU",
    "kripto-cizgi" : "-------------------------------"
}

n_word_list = [
    'NIGGER',
    'NIGGA',
    'NIGG',
    'NIGS',
    'NIGGS',
    'N WORD',
    'N-WORD',
    'N_WORD'
]

currency_map = {
    "ALTIN": ['ALTIN', 'GOLD'],
    "USD": ['USD', 'DOLAR', 'DOLLAR'],
    "EUR": ['EUR', 'EURO', 'AVRO'],
    "GBP": ['GBP', 'POUND', 'STERLIN'],
    "RUB": ['RUB', 'RUBLE'],
    "JPY": ['JPY', 'YEN'],
    "CAD": ['CAD', 'KANADA'],
    "AUD": ['AUD'],
    "CNY": ['CNY', 'RENMINBI'],
    "SEK": ['SWE'],
    "CHF": ['CHW', 'SWI'],
    "DKK": ['DKK', 'DAN'],
    "SAR": ['SAR', 'RIYAL'],
    "RON": ['RON', 'LEY'],
    "NOK": ['NOK'],
    "BGN": ['BGN'],
    "IRR": ['IRR'],
    "PKR": ['PKR'],
    "KWD": ['KWD'],

    # ozel
    "osu": ['osu', 'SUPPORTER', 'SUP'],
    "nitro": ['nitro', 'NITRO']
}

crypto_currency_map = {
    "btc": {'currency': 'bitcoin',          'graph_id': '1',         'aliases': ['BTC', 'BITCOIN']},
    "bch": {'currency': 'bitcoin-cash',     'graph_id': '1831',      'aliases': ['BCH', 'BTCCASH', 'BITCOINCASH']},
    "eth": {'currency': 'ethereum',         'graph_id': '1027',      'aliases': ['ETH', 'ETHEREUM']},
    "xrp": {'currency': 'ripple',           'graph_id': '52',        'aliases': ['XRP', 'RIPPLE']},
    "eos": {'currency': 'eos',              'graph_id': '1765',      'aliases': ['EOS']},
    "xmr": {'currency': 'monero',           'graph_id': '328',       'aliases': ['XMR', 'MONERO']},
    "ltc": {'currency': 'litecoin',         'graph_id': '2',         'aliases': ['LTC', 'LITE', 'LITECOIN']},
    "etc": {'currency': 'ethereum-classic', 'graph_id': '1321',      'aliases': ['ETC', 'ETHEREUM CLASSIC']},
    "zec": {'currency': 'zcash',            'graph_id': '1437',      'aliases': ['ZEC', 'ZCASH']},
    "bcn": {'currency': 'bytecoin-bcn',     'graph_id': '372',       'aliases': ['BCN', 'BYTECOIN']},
    "xlm": {'currency': 'stellar',          'graph_id': '512',       'aliases': ['XLM', 'STELLAR']},
    "ada": {'currency': 'cardano',          'graph_id': '2010',      'aliases': ['ADA', 'CARDANO']},
    "miota": {'currency': 'iota',           'graph_id': '1720',      'aliases': ['MIOTA', 'IOTA']},
    "trx": {'currency': 'tron',             'graph_id': '1958',      'aliases': ['TRX', 'TRON']},
    "neo": {'currency': 'neo',              'graph_id': '1376',      'aliases': ['NEO']},
    "nty": {'currency': 'nexty',            'graph_id': '2714',      'aliases': ['NTY', 'NEXTY']},
    "ppc": {'currency': 'peercoin',         'graph_id': '5',         'aliases': ['PPC', 'PEERCOIN']},
}